madeofpendletonwool/PinePods

internal_functions/modern-nav.py
internal_functions/navbar.py
pypods.py

Merging in side menu. It works and buttons link properly for episode displays which is next.

Side Menu Complete. With functional buttons. Next will be home screen

---

README.md
app_functions/functions.py
customlogin.py
database_functions/functions.py
docker-compose.yml
imageissue.py
imageserver/dockerfile
imageserver/image.py
imageserver/requirements.txt
imageserver/wsgi.py
loginexample.py
pypods.py
requirements.txt

Users now entirely work. There's a login screen on boot and it only allows login if you're added to the Users table in the database.

Login screen - user functionality now added

---

Auth/Passfunctions.py
database_functions/functions.py
pypods.py

This should fix the issue where the database times out after a period of time on the browser

sql pools implemented.

---

README.md
api_functions/functions.py
clients/clientapi.py
clients/database_functions/functions.py
database_functions/functions.py
docker-compose.yml
dockerfile
pypods.py
startup/setupdatabase.py

This allows a setting to disable downloads in settings. For public based servers with self service user creation this is needed.

Ability to disable downloads implemented

---

.gitignore
Backend/pypodsapicall.py
internal_functions/functions.py

In otherwords the backend now supports itunes

Added itunes to the search api

---

.gitignore
.idea/PyPods.iml
.idea/misc.xml
README.md
api_functions/functions.py
app_functions/functions.py
clients/clientapi.py
clients/linux-app/api_functions/functions.py
clients/linux-app/pinepods.py
database_functions/functions.py
layout.py
pypods.py
requirements.txt
startup/setupdatabase.py

Everything now updates as you click. It's all dynamic. Most things got major overhauls and the download system is now way more usable.

Merge in complete layout overhaul

---

clients/linux-app/install.sh

As discussed on Discord, editing this line fixes the Linux desktop client install.

Fix Linux install script

---

api_functions/functions.py
clients/clientapi.py
clients/linux-app/api_functions/functions.py
clients/linux-app/pinepods.py
completed_todos.md
database_functions/functions.py

Bump to 0.4.1. This update lays the ground work for additional client creation that can connect to the Pinepods APIs. Which is the next thing I'm working on. Next to come is finalizing the first version of the TUI client and support for Gpodder APIs. Version 0.5 will include the first edition of Gpodder support

0.4.1 - Version Bump

---

clients/clientapi.py
completed_todos.md
web/src-tauri/tauri.conf.json
web/src/components/episodes_layout.rs
web/src/components/gen_funcs.rs
web/src/components/login.rs
web/src/components/setting_components/user_settings.rs
web/src/requests/search_pods.rs
web/src/requests/setting_reqs.rs

Adding some nice to haves

---

README.md

Probably the contentious point of what I'm proposing is that under the "features" heading it implies more DBs than MySQL and Postgres might be supported. I didn't really know one way or the other, so didn't want to change that sentence too much.

docs: Fix up some typos/grammar, and provide better links

---

web/src/components/home.rs
web/src/components/settings.rs
web/src/requests/login_requests.rs

This adds checks to verify is state exists before loading the component. Which was previously causing a crash if you refreshed on that particular page

Fixed issue with settings component refreshing

---

completed_todos.md
startup/setupdatabase.py
startup/setuppostgresdatabase.py
web/src/requests/pod_req.rs

Adjusted bt username and fixed a minor issue where chapters with floating points wouldn't work

Bt user adjustments

---

completed_todos.md
database_functions/functions.py
web/src/components/episode.rs
web/src/requests/pod_req.rs

All episode interaction buttons throughout the app now fully dynamically update correctly.

Dynamic updating episode page buttons

---

startup/setupdatabase.py
startup/setuppostgresdatabase.py
web/Cargo.lock
web/src-tauri/Cargo.toml
web/src/components/setting_components/theme_options.rs

This causes theme settings to dynamically update and also improves the look a bit. Previously it just defaulted to light. This also fixed a startup theme bug. We'll always default to nordic now

Adjust theme to dynamically update

---

web/src/components/audio.rs
web/src/components/downloads.rs
web/src/components/downloads_tauri.rs
web/src/components/gen_components.rs
web/src/components/history.rs
web/src/components/home.rs
web/src/components/people_subs.rs
web/src/components/person.rs
web/src/components/queue.rs
web/src/components/saved.rs
web/src/components/search.rs
web/src/components/virtual_list.rs

This makes it so that when playing an episode it changes the icon to pause when the episode appears somewhere in a list. Anywhere in a list for that matter.

Implemented dynamic play button on episode lists

---

database_functions/functions.py
web/Cargo.toml
web/src/components/app_drawer.rs
web/src/components/audio.rs
web/src/components/downloads.rs
web/src/components/downloads_tauri.rs
web/src/components/episode.rs
web/src/components/episodes_layout.rs
web/src/components/gen_funcs.rs
web/src/components/history.rs
web/src/components/home.rs
web/src/components/login.rs
web/src/components/people_subs.rs
web/src/components/person.rs
web/src/components/podcast_layout.rs
web/src/components/podcasts.rs
web/src/components/queue.rs
web/src/components/saved.rs
web/src/components/search.rs
web/src/components/settings.rs
web/src/components/shared_episode.rs
web/src/components/user_stats.rs
web/src/components/virtual_list.rs
web/static/styles.css

Dynamic play interaction fully complete and merging in. Also fixed issue with android apis (also likely other OS browser audio apis) so that os native scrubbing works

Dynamic play

---

.github/workflows/build-flatpak.yml
clients/clientapi.py
completed_todos.md
database_functions/functions.py
startup/setupdatabase.py
startup/setuppostgresdatabase.py
web/src/components/episodes_layout.rs
web/src/components/setting_components/mod.rs
web/src/components/setting_components/notifications.rs
web/src/components/settings.rs
web/src/requests/pod_req.rs
web/src/requests/setting_reqs.rs

Notifications implemented as an option for users to subscribe to notifications on any particular podcast. ntfy and gotify are both supported.

Implemented Notifications

---

web/Cargo.toml
web/src/components/app_drawer.rs
web/src/components/downloads.rs
web/src/components/downloads_tauri.rs
web/src/components/episode.rs
web/src/components/episodes_layout.rs
web/src/components/gen_funcs.rs
web/src/components/history.rs
web/src/components/home.rs
web/src/components/mod.rs
web/src/components/navigation.rs
web/src/components/people_subs.rs
web/src/components/person.rs
web/src/components/podcast_layout.rs
web/src/components/podcasts.rs
web/src/components/queue.rs
web/src/components/saved.rs
web/src/components/search.rs
web/src/components/settings.rs
web/src/components/user_stats.rs
web/src/main.rs
web/src/requests/login_requests.rs

Also added custom back button component on certain episodes

Fixed issues with back button in browser

---

web/src/components/setting_components/theme_options.rs

Hi,
Thanks for all your hard work, the project is shaping up quickly to be an amazing one!
I wanted to contribute a theme specifically "Catppuccin Mocha Mauve" for the project, I've forked the project and made the changes in my branch.
I hope I'm following procedure by making this PR - please let me know if there's anything that looks wrong in this.
Thanks!

Add Theme - Catppuccin Mocha Mauve

---

clients/clientapi.py
database_functions/functions.py
database_functions/youtube.py
startup/setupdatabase.py
startup/setuppostgresdatabase.py

This seemed like a natural improvement to having 30 hardcoded into `youtube.py`, pls let me know if there's a better idea or I'm missing something

Backend for "Feed Cutoff"

---

clients/clientapi.py
database_functions/functions.py
startup/setupdatabase.py
startup/setuppostgresdatabase.py

- user-level setting
- podcast-level setting
- endpoints to set/get values

Playback Speed Setting
